# Generated by Django 4.0.5 on 2022-06-14 19:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_controller', '0002_inventory_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='content',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
